### ISSUE TITLE
Instructions on how to fund the lightning wallets

### ISSUE THREAD

**Issue by dellagustin** [NGUtech/bitcoin-stack#8]
Hello, in order to open the channels, one first has to fund the corresponding wallets with bitcoins.
I could not find it in the instructions at the readme, but I made it with the commands:
- `bin/stack alice newaddress np2wkh` (took note of the address)
- `bin/stack bitcoin generatetoaddress 101 <alice's new address>`

One potential improvement would be to add to the `generate` command the option to take an additional (optional) parameter that is the target node name, which can be translated to an address using the function `getAddress`.

**Comment by MrHash** [comment]
Well the bitcoin node wallet has plenty of regtest coins in it which you can see with the balance `bin/stack bitcoin getwalletinfo` so you can simply do `bin/stack alice newaddress np2wkh` to get the address and `bin/stack bitcoin sendtoaddress <address> 1.0` with however much you want to send. Make sure you run the transaction spam generator so bitcoind has some fee estimate data to work with (`docker-compose exec demo sh -c "node bitcoin-spam.js"`). As a one liner the above would be `bin/stack bitcoin sendtoaddress $(bin/stack alice newaddress np2wkh | jq '.address' | tr -d '"') 1.0`.

Otherwise you can do as you have done. Probably people are not generating block rewards to a lightning node IRL so maybe just create your own shell script to automate your preferred behaviour :)
